services:
  - type: web
    name: itsm-flask-googleai
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DATABASE_URL
        fromDatabase: false
        value: "<postgresql://postgres:[YOUR-PASSWORD]@db.vibhyipkkedluvgfwnad.supabase.co:5432/postgres>"
      - key: SECRET_KEY
        fromDatabase: false
        value: "<"1=y3*2&zsvcmov4^)cz8+2l*umers!c*-i)q&0e87-@c1_7e$">"
      - key: GOOGLE_API_KEY
        fromDatabase: false
        value: "<AIzaSyCGLMvx9CsirytfXAmtQKga7vbWaI3mHWU>"
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        fromDatabase: false
        value: "<OPTIONAL_SERVICE_ACCOUNT_JSON_CONTENT>"
      - key: SMTP_HOST
        fromDatabase: false
        value: "<smtp.gmail.com>"
      - key: SMTP_PORT
        fromDatabase: false
        value: "465"
      - key: SMTP_USER
        fromDatabase: false
        value: "<armtechbridge@gmail.com>"
      - key: SMTP_PASS
        fromDatabase: false
        value: "<MARaGUL@20011043>"
      - key: APP_BASE_URL
        fromDatabase: false
        value: "https://armtech-serdesk.onrender.com/"
